---
baseURL: 'https://docs.plgd.dev/'
theme: 'plgd'
title: 'plgd docs'
defaultContentLanguage: en
defaultContentLanguageInSubdir: false
enableEmoji: true
footnotereturnlinkcontents: ↩
languageCode: en-us
languages:
  en:
    contentDir: content/en
    languageName: English
    weight: 1
  # de:
  #   contentDir: content/de
  #   languageName: Deutsch
  #   weight: 2
copyright: 'All Rights Reserved © 2020-{year} plgd.dev, s.r.o.'
googleAnalytics: 'GTM-5B8C4RK'
pluralizeListTitles: false
outputs:
  home:
    - HTML
    - RSS
    - REDIR
    - HEADERS
    - ALGOLIA
  section:
    - HTML
    - RSS
mediaTypes:
  text/netlify:
    delimiter: ''
outputFormats:
  REDIR:
    mediatype: text/netlify
    baseName: _redirects
    isPlainText: true
    notAlternative: true
  HEADERS:
    mediatype: text/netlify
    baseName: _headers
    isPlainText: true
    notAlternative: true
  Algolia:
    baseName: "algolia"
    isPlainText: true
    mediaType: "application/json"
    notAlternative: true
  JSON:
    mediaType: "application/json"
    baseName: "data"
    isPlainText: true
caches:
  getjson:
    dir: ':cacheDir/:project'
    maxAge: -1
  getcsv:
    dir: ':cacheDir/:project'
    maxAge: -1
  images:
    dir: ':resourceDir/_gen'
    maxAge: -1
  assets:
    dir: ':resourceDir/_gen'
    maxAge: -1
related:
  threshold: 80
  includeNewer: true
  toLower: false
  indices:
    - name: keywords
      weight: 100
    - name: date
      weight: 10
      pattern: '2006'
imaging:
  resampleFilter: CatmullRom
  quality: 75
  anchor: smart
taxonomies:
  category: categories
params:
  githubRepository: 'https://github.com/plgd-dev/doc/'
  algolia:
    indexName: 'doc'
    apiKey: '31dbe24685b8a1a7025c12098b32df37'
    appId: '42D6VHXINQ'
---