name: Check spelling

on:
  pull_request:
    branches:
      - main

jobs:
  spelling:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Install and run misspell
        run: |
          # check misspelling in all files in repository
          export PATH=${PATH}:`go env GOPATH`/bin
          go get github.com/client9/misspell/cmd/misspell@latest
          misspell -error .
